### ISSUE TITLE
Cannot find installation for app with id

### ISSUE THREAD

**Issue by bcollamore** [philips-software/app-token-action#57]
Rarely, we receive this transient error (on repos for which this is known to normally work)

Error: Cannot find installation for app with id: ***. Did you installed your app in a repo?

There are no other messages in the workflow logs.

**Comment by bcollamore** [comment]
I don't think so. I thought this action was obsolete.

**Comment by npalm** [comment]
action is still used, but not needed anymore for internal actions.
